filters:
  # https://github.com/textlint/textlint-filter-rule-allowlist
  allowlist:
    allow: []
  # https://github.com/textlint/textlint-filter-rule-comments
  comments: true
  # https://github.com/textlint/textlint-filter-rule-node-types
  # node-types:
  #   nodeTypes: []

rules:
  # TODO: Integrate with VS Code

  # https://github.com/textlint-rule/textlint-rule-no-todo
  no-todo: true

  # https://github.com/textlint-rule/textlint-rule-no-start-duplicated-conjunction
  no-start-duplicated-conjunction:
    interval: 2

  # https://github.com/textlint-rule/textlint-rule-max-comma
  max-comma:
    max: 4

  # https://github.com/azu/textlint-rule-no-empty-section
  no-empty-section: true

  # https://github.com/textlint-rule/textlint-rule-no-invalid-control-character
  '@textlint-rule/no-invalid-control-character': true

  # https://github.com/textlint-rule/textlint-rule-no-unmatched-pair
  '@textlint-rule/no-unmatched-pair': true

  # https://github.com/textlint-rule/textlint-rule-no-zero-width-spaces
  no-zero-width-spaces: true

  # https://github.com/iwamatsu0430/textlint-rule-doubled-spaces
  doubled-spaces: true

  # https://github.com/textlint-rule/textlint-rule-no-duplicate-abbr
  '@textlint-rule/no-duplicate-abbr': true

  # https://github.com/azu/textlint-rule-unexpanded-acronym
  # unexpanded-acronym:
  #   min_acronym_len: 3

  # https://github.com/azu/textlint-rule-alex
  # alex:
  #   allow: []
  #   noBinary: true
  #   profanitySureness: 1

  # https://github.com/azu/textlint-rule-rousseau
  # rousseau:
  #   showLevels: [suggestion, warning, error]

  # https://github.com/nodaguti/textlint-rule-write-good
  # write-good: true

  # https://github.com/azu/textlint-rule-en-max-word-count
  en-max-word-count:
    max: 40

  # https://github.com/sapegin/textlint-rule-diacritics
  diacritics: true

  # https://github.com/sapegin/textlint-rule-stop-words
  # stop-words:
  #   defaultWords: true
  #   skip: []
  #   words: []
  # exclude": []

  # https://github.com/textlint-rule/textlint-rule-en-capitalization
  en-capitalization:
    allowWords:
      - superQuery

  # https://github.com/io-monad/textlint-rule-common-misspellings
  common-misspellings:
    ignore: []

  # https://github.com/ta2gch/textlint-rule-spelling
  # spelling:
  #   language: en
  #   skipPatterns: [JavaScript]
  #   wordDefinitionRegexp": /[\\w']+/g
  #   suggestCorrections": true

  # https://github.com/blue-hood/textlint-rule-en-spell
  # en-spell:
  #   personalDictionary: []

  # https://github.com/sapegin/textlint-rule-terminology
  terminology:
    defaultTerms: true
    terms:
      - ABN
      - ACH
      - AICPA
      - Algolia
      - Amazon
      - Amazon Web Services
      - AMTS
      - API
      - ASG
      - ASGs
      - AWS
      - BigQuery
      - BigQuery Lens
      - BRL
      - Budgetao
      - CC
      - CCs
      - CICD
      - CLI
      - Cloud Management Platform
      - CloudFormation
      - CloudHealth
      - CMP
      - CPM
      - CPU
      - CPUs
      - CRM
      - CUD
      - CUDs
      - Customer Relationship Management
      - DACH
      - DKK
      - DoiT
      - DoiT International
      - DoiT International Ltd
      - EBS
      - ECAM
      - ELB
      - End-Customer Account Model
      - FinOps
      - Firestore
      - FlexSave
      - FullStory
      - GBP
      - GCE
      - GCP
      - GCS
      - GKE
      - GmbH
      - Google
      - Google Cloud
      - GPU
      - GPUs
      - High Performance Computing
      - HPC
      - HubSpot
      - IBAN
      - Identity Provider
      - IdP
      - IEC
      - IOPS
      - ISO
      - KPI
      - KPIs
      - Kubernetes
      - Kubernetes Engine
      - Mixpanel
      - MPA
      - MPAs
      - NOK
      - PCI
      - PPU
      - Price Per Unit
      - RBAC
      - RCS
      - RedHat
      - RedHat Enterprise Linux
      - RHEL
      - RI
      - RIs
      - RO
      - SaaS
      - Sarl
      - SDK
      - SKU
      - SKUs
      - SLA
      - SLAs
      - SP
      - SpotScaling
      - SPP
      - SPs
      - SSD
      - SSDs
      - superQuery
      - SuSe
      - SuSe Enterprise Linux
      - TCO
      - UDF
      - UDFs
      - VM
      - VMs
      - VMware
      - VMware Cloud
      - Zendesk
