/**
Creating a sidebar enables you to:

- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.
*/

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  cmpSideBar: [
    {
      type: 'category',
      label: 'Cloud Management Platform',
      link: { type: 'doc', id: 'cmp' },
      items: [{ type: 'autogenerated', dirName: 'cmp' }],
    },
  ],
  superQuerySideBar: [
    {
      type: 'category',
      label: 'superQuery',
      link: { type: 'doc', id: 'superquery' },
      items: [{ type: 'autogenerated', dirName: 'superquery' }],
    },
  ],
  devHubSideBar: [
    {
      type: 'category',
      label: 'Developer Hub',
      link: { type: 'doc', id: 'developer-hub' },
      items: [{ type: 'autogenerated', dirName: 'developer-hub' }],
    },
  ],
};

module.exports = sidebars;
